### ISSUE TITLE
dpp::cluster::thread_create_in_forum() crashes the bot without a clear error when the bot has insufficient permissions 

### ISSUE THREAD

**Issue by NaJager** [brainboxdotcc/DPP#577]
**Git commit reference**
d4b74dae5a3fd7d2f7e9f458c90c16c4fc4fa588

**Describe the bug**
When dpp::cluster::thread_create_in_forum() is used in a channel where the bot does not have the correct permissions to create a post, the bot crashes without any clear errors (see screenshot further down). 

run dpp::cluster::thread_create_in_forum() on a channel the bot does not have the Create Posts permission for

**Expected behavior**
Something along the lines of what bot.message_create() would do in the case of missing permissions: Outputting an error code along with the API response to the terminal, showing that the bot does not have the correct permissions. And most importantly, not crash the bot in the process. 

Currently however, the bot just terminates with little information about the reason, see screenshot
![image](https://user-images.githubusercontent.com/84308084/206813841-3eb3de5d-e6ab-4984-b8ae-53454af6ef4c.png)

 - OS: Ubuntu 20.04.5 LTS x86_64

**Comment by braindigitalis** [comment]
please try latest master, I think this is already fixed

**Comment by NaJager** [comment]
I updated to 572f41b70dccc63f0f952885ac96308f7f2065f6 and am still having this issue. Unless git show -s --format="%H" isn't giving me the actual version I'm using ¯\_(ツ)_/¯

**Comment by Commandserver** [comment]
I couldn't reproduce the issue. Can you please share your code so we can figure this out?

**Comment by NaJager** [comment]
test.cpp:
`#include <dpp/dpp.h>

int main() {
    dpp::cluster bot(TOKEN_HERE, dpp::i_default_intents);
    bot.on_log(dpp::utility::cout_logger());

    bot.on_ready([&bot](const dpp::ready_t& event) {
        dpp::message msg("Test message");

        // forum channel the bot does have the permissions to post to for
        bot.thread_create_in_forum("Correct Permissions", 1051197575262375967, msg, dpp::arc_1_day, 0);

        // forum channel the bot does not have the permissions to post to for
        bot.thread_create_in_forum("Insufficient Permissions", 1051197629628948490, msg, dpp::arc_1_day, 0);
    });

    bot.start(false);
}`
compiled using `g++ -o test test.cpp -ldpp -std=c++17 -Wall -L/usr/lib`
The bot successfully creates the first thread, then exits with `[json.exception.type_error.305]` as shown in the screenshot above

**Comment by Commandserver** [comment]
alright thanks for reporting. Should be fixed in the dev branch and soon in master

**Comment by NaJager** [comment]
Confirmed that this does fix the issue, thanks a lot!
